import { ChannelType } from 'discord.js';
import { KyraUI } from '#classes/KyraUI';

export default {
    name: 'geninvite',
    description: 'Generates an invite link for a specific guild ID.',
    aliases: ['gi', 'invitegen'],
    ownerOnly: true,
    async execute({ client, message, args }) {
        const guildId = args[0];
        if (!guildId) {
            return message.reply({ components: KyraUI.buildSimpleMessage(`${client.config.emojis.error} Please provide a Guild ID.`), flags: KyraUI.getFlags() });
        }

        const guild = client.guilds.cache.get(guildId);
        if (!guild) {
            return message.reply({ components: KyraUI.buildSimpleMessage(`${client.config.emojis.error} I am not in that guild.`), flags: KyraUI.getFlags() });
        }

        try {
            // Find the best channel to create an invite
            const channel = guild.channels.cache.find(c => 
                c.type === ChannelType.GuildText && 
                c.permissionsFor(guild.members.me).has('CreateInstantInvite')
            ) || guild.channels.cache.first();

            if (!channel) {
                return message.reply({ components: KyraUI.buildSimpleMessage(`${client.config.emojis.error} I couldn't find any channel to create an invite in.`), flags: KyraUI.getFlags() });
            }

            const invite = await channel.createInvite({
                maxAge: 0, // Never expires
                maxUses: 0, // Unlimited uses
                reason: `Generated by owner: ${message.author.tag}`
            });

            const successContainer = KyraUI.buildDetailedDashboard(
                `### ${client.config.emojis.success} **Invite Generated**`,
                `Successfully generated an invite for **${guild.name}**.`,
                [
                    { name: '🔗 Link', value: `${invite.url}` },
                    { name: '📁 Channel', value: `${channel.name} (<#${channel.id}>)` },
                    { name: '🆔 Guild ID', value: `\`${guild.id}\`` }
                ]
            );

            await message.reply({ components: successContainer, flags: KyraUI.getFlags() });
        } catch (error) {
            client.logger.error('GenInvite', `Error generating invite for ${guildId}:`, error);
            return message.reply({ components: KyraUI.buildSimpleMessage(`${client.config.emojis.error} Failed to generate invite. Ensure I have the **Create Instant Invite** permission.`), flags: KyraUI.getFlags() });
        }
    }
};
